# Generated by Django 3.2.5 on 2022-01-23 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=datetime.datetime(2022, 1, 23, 16, 46, 59, 492005))),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID'), ('deleted', 'DELETED')], default='pending', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=210)),
                ('dni', models.CharField(max_length=10)),
                ('guest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntervalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'SINGLE'), ('double', 'DOUBLE'), ('triple', 'TRIPLE'), ('quad', 'QUAD'), ('queen', 'QUEEN'), ('king', 'KING'), ('double-double', 'DOUBLE_DOUBLE'), ('suite', 'SUITE')], default='single', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'CASH'), ('debit card', 'DEBIT_CARD'), ('credit card', 'CREDIT_CARD'), ('mobile payment', 'MOBILE_PAYMENT'), ('electronic bank transfer', 'ELECTRONIC_BANK_TRANSFER')], default='cash', max_length=24)),
                ('amount', models.PositiveSmallIntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 1, 23, 16, 46, 59, 493009))),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='booking.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='booking.intervaldate'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customers',
            field=models.ManyToManyField(to='booking.Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='booking.room'),
        ),
    ]
